### ISSUE TITLE
The 'rcnn' module required in run_rcnn.py is missing

### ISSUE THREAD

**Issue by stupidHIGH** [ShannonAI/OpenViDial#10]
I‘m trying to extract rcnn features by myself using provided 'run_rcnn.py' script, however the missing module 'rcnn' is required in line 38.
```python
from rcnn.dataset import get_dataloader
```

So where can I find the _**get_dataloader**_ function ?
THX

**Comment by YuxianMeng** [comment]
@stupidHIGH 
Hi, `rcnn` is [this repo](https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark), which is the first step of extracting Faster-RCNN feature in extract_features.md

**Comment by YuxianMeng** [comment]
Hi @stupidHIGH, thanks for pointing out this issue. I have updated the related code, you can pull the latest code and check whether this issue has been fixed.
