### ISSUE TITLE
10.zip is 414K?

### ISSUE THREAD

**Issue by wjczf123** [ShannonAI/OpenViDial#19]

**Comment by wjczf123** [comment]
Is it right?

**Comment by YuxianMeng** [comment]
@wjczf123 
It is right. It is because that 0.zip~10.zip are previous training dataset(~900k), and 11.zip is the previous validation dataset(~100k)，and we put them together to get the new dataset(~1M).

**Comment by wjczf123** [comment]
OK. Thank u a lot.
