### ISSUE TITLE
result

### ISSUE THREAD

**Issue by wjczf123** [ShannonAI/OpenViDial#20]
Hi,
  I run your code (text_only). I get the gen.out file. The result seems that (Last line in gen.out):
Generate test with beam=5: BLEU4 = 1.21, 15.6/1.4/0.5/0.2 (BP=0.953, ratio=0.954, syslen=370561, reflen=388568)

The results are correct? What means that results? Do the results include BLEU-1, BLEU-2, BLEU-4, Dis-1, Dis-2, Dis-3, and Dis-4?

**Comment by YuxianMeng** [comment]
@wjczf123 your result means that BLEU4 is 1.21. The results looks correct. As fairseq toolkit only calculate BLEU4, you should write your own scripts to get BLEU1~3. Other statistics like `Dis` could be calculated by `train/stats.py`

**Comment by wjczf123** [comment]
OK. Thank you for your reply. Thank you a lot.
