### ISSUE TITLE
result

### ISSUE THREAD

**Issue by wjczf123** [ShannonAI/OpenViDial#21]
I run your code of NV and CV model. The BLEU-4 is 1.21 and 1.22 respectively.
Then I use grep ^D gen.out | cut -f3- > sys.txt to get the sys.txt.
But the performance is poor.

=====Stats of /deepo_data/sys_NV.txt=====
Diversity-1: 0.0028171826554375134
Diversity-2: 0.012234149152032867
Diversity-3: 0.02608896729461698
Diversity-4: 0.04205556064912441
StopWords%: 0.5369782208034367; StopWords/Sent: 3.8842692900782727
AvgLength: 7.233569518455623
=====Stats of /deepo_data/sys_CV.txt=====
Diversity-1: 0.0029348115275008298
Diversity-2: 0.012985147977712393
Diversity-3: 0.027433267080460996
Diversity-4: 0.04410504609184471
StopWords%: 0.5485848448526971; StopWords/Sent: 3.9040424742831488
AvgLength: 7.116570045480276

The stopwords seem normal. But the diversity performances pool. The line of sys_NV and sys_CV are both 51231.
[sys_CV.txt](https://github.com/ShannonAI/OpenViDial/files/6087924/sys_CV.txt)

**Comment by wjczf123** [comment]
I notice that ''1: we times Dis-x by 10 for the ease of demonstration'' in the demo (but not found in the paper).
Then my results of NV model are 0.0282, 0.1223, 0.2609, 0.4206?
This looks much better than the results reported in the demo.

**Comment by YuxianMeng** [comment]
@wjczf123 Hi, the current results in our paper is evaluated on the older version(900k/100k/100k for train/valid/test) of data. We're re-running the experiments in the new data(1M/50k/50k) and will update the metrics soon.

**Comment by wjczf123** [comment]
OK. Thank you.

**Comment by YuxianMeng** [comment]
@wjczf123 We just found that the cnn/rcnn features of valid/test dataset are incorrect. We'll let you know as soon as files are updated!

**Comment by wjczf123** [comment]
OK. Thank you a lot!

**Comment by wjczf123** [comment]
@YuxianMeng I am not familiar with fairseq. But we found that we can use this code to enhance your code (line 384 in train.generate.py) with BLEU-1 and BLEU-2:

        print(
            "Generate {} with beam={}: {}".format(
                args.gen_subset, args.beam, scorer.result_string()
            ),
            file=output_file,
        )  # BLEU-4

        print(
            "Generate {} with beam={}: {}".format(
                args.gen_subset, args.beam, scorer.result_string(2)
            ),
            file=output_file,
        )  #BLEU-2

        print(
            "Generate {} with beam={}: {}".format(
                args.gen_subset, args.beam, scorer.result_string(1)
            ),
            file=output_file,
        )  # BLEU-1
I run this (text only), the results is:
Generate test with beam=5: BLEU4 = 1.21, 15.6/1.4/0.5/0.2 (BP=0.953, ratio=0.954, syslen=370561, reflen=388568)
Generate test with beam=5: BLEU3 = 2.16, 15.6/1.4/0.5 (BP=0.953, ratio=0.954, syslen=370561, reflen=388568)
Generate test with beam=5: BLEU2 = 4.52, 15.6/1.4 (BP=0.953, ratio=0.954, syslen=370561, reflen=388568)
Generate test with beam=5: BLEU1 = 14.82, 15.6 (BP=0.953, ratio=0.954, syslen=370561, reflen=388568)

BLEU seems to be correct, even if other things seem to be problematic.

**Comment by YuxianMeng** [comment]
@wjczf123 Nice work! You're welcome to open a PR to our project! BTW, I do not see anything problematic in your results, could you point out the parts that you think are problematic ?

**Comment by wjczf123** [comment]
@YuxianMeng I am not familiar with fairseq. I don't know what the latter result (i.e., 15.6/1.4/0.5/0.2 (BP=0.953, ratio=0.954, syslen=370561, reflen=388568)) means.  I see that they are same. Then I I suspect there is a problem.  Finally, I finish my RP. Thank you for your help.

**Comment by YuxianMeng** [comment]
@wjczf123 Thanks for your PR! As for your concern, those numbers should be the same according to the formula of BLEU :)
