### ISSUE TITLE
problem when run FineVisual model

### ISSUE THREAD

**Issue by phellonchen** [ShannonAI/OpenViDial#22]
There is a bug as follows:
mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size

The size of object features files:
149G	train.objects.mmap
11G	train.objects.mmap.splitaa
11G	train.objects.mmap.splitab
11G	train.objects.mmap.splitac
11G	train.objects.mmap.splitad
11G	train.objects.mmap.splitae
11G	train.objects.mmap.splitaf
11G	train.objects.mmap.splitag
11G	train.objects.mmap.splitah
11G	train.objects.mmap.splitai
11G	train.objects.mmap.splitaj
11G	train.objects.mmap.splitak
11G	train.objects.mmap.splital
11G	train.objects.mmap.splitam
2.1G	train.objects.mmap.splitan
17G	train.objects.mmap.splitao

**Comment by YuxianMeng** [comment]
@phellonchen Thanks for your feedback! It's due to the wrong default value of one parameter, which I changed in [this PR](https://github.com/ShannonAI/OpenViDial/pull/23/files), could you please try to revise your code accordingly, and tell my is the bug fixed?

**Comment by phellonchen** [comment]
> @phellonchen Thanks for your feedback! It's due to the wrong default value of one parameter, which I changed in [this PR](https://github.com/ShannonAI/OpenViDial/pull/23/files), could you please try to revise your code accordingly, and tell my is the bug fixed?

Thanks. Fixed.

**Comment by YuxianMeng** [comment]
@phellonchen FYI: We just found that the cnn/rcnn features of valid/test dataset are incorrect. We'll let you know as soon as files are updated.
