### ISSUE TITLE
How to preprocess data on my own?

### ISSUE THREAD

**Issue by stupidHIGH** [ShannonAI/OpenViDial#9]
The script provided to preprocess text data only can binarize the **.txt** files into **.bin** files.
How to get files like **train.sent_num.npy** exactly?
THX

**Comment by YuxianMeng** [comment]
@stupidHIGH please see `preprocess/preprocess_video_data.py`

**Comment by stupidHIGH** [comment]
> 
> 
> @stupidHIGH please see `preprocess/preprocess_video_data.py`

Thank you！
